services:
  web1:
    image: nginx:1.27.2
    volumes:
      - ./web1/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web1/html:/usr/share/nginx/html:ro
    ports:
      - "81:80"
  web2:
    image: nginx:1.27.2
    volumes:
      - ./web2/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web2/html:/usr/share/nginx/html:ro
    ports:
      - "82:80"
  haproxy:
    image: haproxy:3.0.5
    volumes:
    #  - ./haproxy:/haproxy-override
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    links:
      - web1
      - web2
    ports:
      - "80:80"
      - "70:70" # haproxy admin console, login with user:pass

networks:
  my-infra-net:
